### ISSUE TITLE
Can't seem to find package ighelper used in Network notebook example

### ISSUE THREAD

**Issue by hanisaf** [vtraag/4TU-CSS#1]
Thanks for putting together this great tutorial. I can't seem to find the package ighelper, it is not listed in PIP either. 

thanks

**Comment by vtraag** [comment]
You're welcome. The ighelper is just a python file located in the same directory in the repository, so make sure you download that as well. Or just clone the entire repository.

**Comment by hanisaf** [comment]
Thanks!
