### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by emoriebeck** [vtraag/4TU-CSS#2]
The notebook does not appear to load.

**Comment by vtraag** [comment]
Do you have some more details?

**Comment by emoriebeck** [comment]
![image](https://cloud.githubusercontent.com/assets/22037413/25048370/d61e5258-2101-11e7-93c1-22d514a62053.png)

![image](https://cloud.githubusercontent.com/assets/22037413/25048412/07feece2-2102-11e7-94b1-b9d31a34191c.png)

I've tried on different web browsers and computers.

**Comment by vtraag** [comment]
This is presumably a problem in how GitHub itself tries to present the notebook. I'll check it out. But if you download the notebook and run it in jupyter, it should work fine.It's easiest to clone the whole repository, otherwise ensure that you have also downloaded the `ighelper.py` file.

**Comment by vtraag** [comment]
It loads fine in my browser on my laptop (although it doesn't work on my mobile). What browser, what OS and what system (CPU & memory) are you on?
